### PR TITLE
Allow user to override metadata properties (e.g. $ip, $ignore_time)

### PR DESCRIPTION
**Pull request by ghost**
This also covers the same features requested in Pull Request #9 and Issue #8 .  Tests included.

### CODE REVIEW

**Comment by rafaelcgo** [comment]
@joeatwork  and @sbnoemi 
I'm using this library on desktop applications, not servers, so I would like to track IP requests in order to get some geolocation info.

How can I achieve that? Write my own `Consumer`, overwriting the `_write_request` method to not set `ip=0`?

I've found out I can send `people_set(distinct_id, properties, meta={'$ip': 'xxx.xxx.xxx.xxx'}` and it works, but for `track` or `import_data` `meta={'ip'=''}` or `meta={'$ip'=''}` won't work. What I'm doing wrong here?
Still, this approach would make me fetch my external IP at each request, which is not optimal. The best solution would be sending the request and letting Mixpanel find out which ip I'm using.

**Comment by zakj** [comment]
Hi @rafaelcgo. Yes, the easiest solution would be for you to create a custom `Consumer` that sets `'ip': 1` in the `data` dict in `_write_request`. See also the description of our API at <https://mixpanel.com/help/reference/http#tracking-events>.

**Comment by rafaelcgo** [comment]
@zakj  I implemented a new Consumer with `_write_request`, only changing the `ip` to `1`. I even placed a `print` inside that method in order to debug it, and it seems that `_write_request` from my consumer is never been called (but the requests are being sent to mixpanel).

Can you understand what I'm doing wrong here?

```
import json

from mixpanel import Consumer
from mixpanel import MixpanelException
from f_sqlite_analytics_database import FSQLiteAnalyticsDatabase

class FSqliteAsyncBufferedConsumer(Consumer):
    def __init__(self, events_url=None, people_url=None, import_url=None, *args, **kwargs):
        super(FSqliteAsyncBufferedConsumer, self).__init__(
            events_url=events_url,
            people_url=people_url,
            import_url=import_url
        )

        self.db = FSQLiteAnalyticsDatabase('consumer')

    def send(self, endpoint, json_message, api_key=None):
        # api_key will be ignored, AnalyticsWorker will get it from FMixpanelInitializer and use it
        if endpoint not in self._endpoints:
            raise MixpanelException('No such endpoint "{0}". Valid endpoints are one of {1}'.format(endpoint, self._endpoints.keys()))
        self.db.createItem(endpoint, json_message)

    def flush(self, endpoint=None, async=True):
        return True

    # Re-writing _write_request from Mixpanel Consumer in order to track 'ip'
    # Any changes on Mixpanel original Consumer needs to be reflected here
    # https://github.com/mixpanel/mixpanel-python/blob/master/mixpanel/__init__.py
    def _write_request(self, request_url, json_message, api_key=None):
        print "WRITE REQUEST"
        data = {
            'data': base64.b64encode(json_message.encode('utf8')),
            'verbose': 1,
            'ip': 1, # Chaging to track ip from requests
        }
        if api_key:
            data.update({'api_key': api_key})
        encoded_data = urllib.parse.urlencode(data).encode('utf8')
        try:
            request = urllib.request.Request(request_url, encoded_data)

            # Note: We don't send timeout=None here, because the timeout in urllib2 defaults to
            # an internal socket timeout, not None.
            if self._request_timeout is not None:
                response = urllib.request.urlopen(request, timeout=self._request_timeout).read()
            else:
                response = urllib.request.urlopen(request).read()
        except urllib.error.URLError as e:
            six.raise_from(MixpanelException(e), e)

        try:
            response = json.loads(response.decode('utf8'))
        except ValueError:
            raise MixpanelException('Cannot interpret Mixpanel server response: {0}'.format(response))

        if response['status'] != 1:
            raise MixpanelException('Mixpanel error: {0}'.format(response['error']))

        return True

```

**Comment by zakj** [comment]
@rafaelcgo It looks like your new `Consumer` subclass isn't calling `_write_request` anywhere—our normal `Consumer` calls it from `send`, where you're just inserting into a database. Looks like finishing up your `flush` implementation might be the right spot in this case.

**Comment by rafaelcgo** [comment]
@zakj Got it! Actually I'm sending the events using another thread, which reads from DB. I was using `Consumer` `send()`, which obviously wasn't using `_write_request` from my `FSqliteAsyncBufferedConsumer`. I've implemented a method called `send_now` inside `FSqliteAsyncBufferedConsumer` and I'm using it to send the requests to Mixpanel server. Working great. Thanks for the support.

**Comment by zakj** [comment]
@rafaelcgo Awesome, glad to hear you figured it out! :)

**Pull request merged**
