### PR TITLE
Call MixpanelException on general URLError

### PR DESCRIPTION
**Pull request by naoyak**
In our implementation we were intermittently experiencing connectivity issues causing this error:

```
File "/home/ubuntu/.virtualenvs/gb/local/lib/python2.7/site-packages/mixpanel/__init__.py", line 74, in track
    self._consumer.send('events', json.dumps(event, separators=(',', ':')))
  File "/home/ubuntu/.virtualenvs/gb/local/lib/python2.7/site-packages/mixpanel/__init__.py", line 335, in send
    self._write_request(self._endpoints[endpoint], json_message, api_key)
  File "/home/ubuntu/.virtualenvs/gb/local/lib/python2.7/site-packages/mixpanel/__init__.py", line 350, in _write_request
    response = urllib2.urlopen(request).read()
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 394, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 412, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1209, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1171, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 104] Connection reset by peer>
```

This PR proposes to trigger a `MixpanelException` on the more general `URLError` in place of `HTTPError`.

### CODE REVIEW

**Comment by joeatwork** [comment]
This seems like the right fix! Thanks for the contribution!

**Comment by naoyak** [comment]
@joeatwork does this still seem useful? I know there was another merged PR in the meantime but AFAIK this was a separate issue.

**Comment by joeatwork** [comment]
That PR was for a separate issue, I think your PR is something I'd like to see in the release.

**Comment by llllllllll** [comment]
I am wondering what the status of the PR is; we currently have a workaround for `ECONNRESET` in our app; however, this would be really awesome.

**Comment by joeatwork** [comment]
We still want this feature in a release, but it may be a bit until we merge it- we're trying to come up with am error handling story that works with possibly asynchronous consumers and still stays appropriately out of user's face in simple cases. It's almost certain, however, that this PRQ will get in in some form eventually.

Sorry I don't have an ETA- you're welcome to check back here (or even ping support) if you've got issues you're interested in.

**Comment by DavidMuller** [comment]
During the mixpanel service disruption yesterday, `URLError: <urlopen error [Errno 104] Connection reset by peer>` cropped up a number of times for us.  Our application simply abandoned writes (instead of retrying) because (as per the documentation) we were only preparted to handle `MIxpanelException` and not more generic urllib errors.

screen shot 2016-01-21 at 8 19 36 am

Any thoughts on this PR -- it seems like a reasonable change to catch [all urllib errors](https://docs.python.org/3.1/library/urllib.error.html) instead of just the HTTPError subset?

**Comment by zakj** [comment]
Landed as a8c73de and released in 4.3.0. Thanks for this @naoyak, and sorry it took us so long!

**Pull request closed without merging**
