### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by llllllllll**
Addresses: https://github.com/mixpanel/mixpanel-python/issues/29

Fixes the module docstring, and the docstring for `Mixpanel.track`.

### CODE REVIEW

**Comment by joeatwork** [comment]
This fixes a kind of serious bug (spooky persistent stuff in the stateful default arguments) and is also a generally nice PRQ! Thanks!

**Comment by llllllllll** [comment]
No problem, I didn't even realize that there was already a bug from this, I merely popped in to clean up the docstring and figured it couldn't hurt

**Comment by zakj** [comment]
Merged this and released 4.0.1. Thanks again!

**Comment by llllllllll** [comment]
Thank you for providing the API.

**Pull request closed without merging**
