### PR TITLE
Serialise datetimes to JSON

### PR DESCRIPTION
**Pull request by alexlouden**

### CODE REVIEW

**Comment by joestump** [comment]
Any chance of getting this merged? Was about to submit a similar PR.

**Comment by cevaris** [comment]
+1 Need to be able to handle datetime objects

**Comment by zakj** [comment]
Yep, this looks like an easy win—so sorry for the delay, everyone! I'll get this merged by the end of next week.

**Comment by zakj** [comment]
Merged and released as 4.0.1. Thanks again, @alexlouden!

**Comment by alexlouden** [comment]
My pleasure!

On Monday, March 9, 2015, Zak Johnson <notifications@github.com> wrote:

> Merged and released as 4.0.1. Thanks again, @alexlouden
> <https://github.com/alexlouden>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mixpanel/mixpanel-python/pull/28#issuecomment-77974467>
> .
>


-- 
Alex

**Pull request closed without merging**
